innov_web/Controllers/GroupController.cs
using innov_web.Models.DTO;
using innov_web.Services;
using innov_web.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace innov_web.Controllers
{
    public class GroupController : Controller
    {
        private readonly IGroupService _groupService;
        public GroupController(IGroupService groupService)
        {
            _groupService = groupService;
        }
        public async Task<IActionResult> Index()
        {
            List<GroupDto> list = new();

            var response = await _groupService.GetAllAsync<APIResponse>();
            if (response != null && response.IsSuccess)
            {
                list = JsonConvert.DeserializeObject<List<GroupDto>>(Convert.ToString(response.Result));
            }
            return View(list);
        }
        public async Task<IActionResult> GroupCreate()
        {
            GroupCreateDto groupDto = new();
            return View(groupDto);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> GroupCreate(GroupDto model)
        {
            // var errors = ModelState.Values.SelectMany(v => v.Errors);
            if (ModelState.IsValid)
            {
              
                model.ConnectionString = (model.ConnectionString).Replace(@"\\", @"\");
                var response = await _groupService.CreateAsync<APIResponse>(model);
                if (response != null && response.IsSuccess)
                {
                    TempData["success"] = "Group created successfully";
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    if (response.ErrorMessages.Count > 0)
                    {
                        ModelState.AddModelError("ErrorMessages", response.ErrorMessages.FirstOrDefault());
                    }
                }
            }
            TempData["error"] = "Error encountered.";
            return View(model);
        }
        public async Task<IActionResult> GroupVerbs(int groupId)
        {

            var groupVerbs = new GroupVerbsDto();
            var response = await _groupService.GetGroupVerbsAsync<APIResponse>(groupId);
            if (response != null && response.IsSuccess)
            {
                 groupVerbs = JsonConvert.DeserializeObject<GroupVerbsDto>(Convert.ToString(response.Result));
            }
            groupVerbs.Id = groupId;
            return View(groupVerbs);
        }

    }
}

innov_web/Controllers/VerbController.cs
using innov_web.Models.DTO;
using innov_web.Models.VM;
using innov_web.Services;
using innov_web.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using innov_web.Models.DTO;

namespace innov_web.Controllers
{
    public class VerbController : Controller
    {
        private readonly IGroupService _groupService;
        private readonly IVerbService _verbService;
        public VerbController(IGroupService groupService, IVerbService verpService)
        {
            _groupService = groupService;
            _verbService = verpService;
        }
        public async Task<IActionResult> VerbCreate(int groupId)
        {
            CreateVerbVM createVerbVm = new();
            createVerbVm.Verb.GroupId = groupId;
            var response = await _groupService.GetAllAsync<APIResponse>();
            var tableRepsonse = await _verbService.GetTablesNamesAsync<APIResponse>(groupId);

            if (response != null && response.IsSuccess && tableRepsonse != null && tableRepsonse.IsSuccess)
            {
                createVerbVm.GroupList = JsonConvert.DeserializeObject<List<GroupDto>>
                    (Convert.ToString(response.Result)).Select(i => new SelectListItem
                    {
                        Text = i.Name,
                        Value = i.Id.ToString()
                    });
                createVerbVm.TableList = JsonConvert.DeserializeObject<List<TableDto>>
                     (Convert.ToString(tableRepsonse.Result)).Select(i => new SelectListItem
                     {
                         Text = i.Name,
                     });
            }
            return View(createVerbVm);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> VerbCreate( CreateVerbVM model)
        {
            model.Verb.Paramters = new List<ParamtersDto>();
            //if (!model.CheckParams)
            //{
            //    model.Verb.Paramters.Clear();
            //}
            IEnumerable<ModelError> allErrors = ModelState.Values.SelectMany(v => v.Errors);
           
                
                
                var response = await _verbService.CreateAsync<APIResponse>(model.Verb);
                if (response != null && response.IsSuccess)
                {
                    TempData["success"] = "Verb created successfully";
                    return RedirectToAction("GroupVerbs", "Group", new { groupId = model.Verb.GroupId });
                }
                else
                {
                    if (response.ErrorMessages.Count > 0)
                    {
                        ModelState.AddModelError("ErrorMessages", response.ErrorMessages.FirstOrDefault());
                    }
                }
            
            return RedirectToAction("GroupVerbs", "Group", new { groupId = model.Verb.GroupId });
        }
        public async Task<IActionResult> TestEndPoint(int verbId)
        {

            List<ParamtersDto> list = new();

            var response = await _verbService.GetParamtersAsync<APIResponse>(verbId);
            if (response != null && response.IsSuccess)
            {
                list = JsonConvert.DeserializeObject<List<ParamtersDto>>(Convert.ToString(response.Result));
            }
            var verbResponse = await _verbService.GetVerbAsync<APIResponse>(verbId);
            VerbDto verb = new VerbDto();
            if (verbResponse != null && verbResponse.IsSuccess)
            {
                 verb = JsonConvert.DeserializeObject<VerbDto>(Convert.ToString(verbResponse.Result));
            }
            TestVM testVm = new TestVM()
            {
                Paramters = list,
                Verb = verb
            };
            return View(testVm);
        }
        

    }
}

innov_web/Views/Group/GroupCreate.cshtml
@model innov_web.Models.DTO.GroupCreateDto

<form asp-action="GroupCreate">
    <br />
    <div class="container border p-3">
        <h1 class="text-primary">Create Group</h1>
        <hr />

        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="col-2">
                <label asp-for="Name" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="col-2">
                <label asp-for="DbType" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <select asp-for="DbType" class="form-select">
                    <option disabled selected>--Select Type--</option>
                    <option>SQL</option>
                    
                </select>
                <span asp-validation-for="DbType" class="text-danger"></span>
            </div>
            <div class="col-2">
                <label asp-for="ConnectionString" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="ConnectionString" class="form-control" />
                <span asp-validation-for="ConnectionString" class="text-danger"></span>
            </div>
            <div class="col-5">
                <input type="submit" value="Create" class="btn btn-success form-control" />
            </div>
        </div>
    </div>
</form>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

innov_web/Views/Group/GroupVerbs.cshtml
@model innov_web.Models.DTO.GroupVerbsDto
<div class="container">

    <a asp-controller="Verb" asp-action="VerbCreate" asp-route-groupId="@Model.Id" class="btn btn-outline-primary"><i class="bi bi-plus-square-fill"></i> Create New End Point</a>
    <br />
    <h2>@Model.GroupName -- End Points</h2>
    
    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Type</th>

            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.verbsDto)
            {
                <tr>
                    <td>@item.Name</td>
                    <td>@item.Type</td>

                </tr>
            }
        </tbody>
    </table>
</div>
<script>
   
</script>

innov_web/Views/Group/Index.cshtml
@model IEnumerable<innov_web.Models.DTO.GroupDto>
<div class="container">
    <a asp-controller="Group" asp-action="GroupCreate" class="btn btn-outline-primary"><i class="bi bi-plus-square-fill"></i> Create New Group</a>


    <h2>Groups</h2>
    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>End Points</th>

            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Name</td>
                    <td><a class="btn btn-primary" asp-controller="Group" asp-action="GroupVerbs" asp-route-groupId="@item.Id">End Points</a></td>
                  
                </tr>
            }
        </tbody>
    </table>
</div>
<script>
   
</script>